/****************************
	ROCK PAPER SCISSORS GAME
	
	This programs simulates the Rock/Paper/Scissors Game
	
	Tom Gallagher
	March 2019
	CSCI 113
	Programming Assignment 3
	
*****************************/
#include <iostream>
using namespace std;

// Global Constants 
const int ROCK=0, PAPER=1, SCISSORS=2;
const int COMPUTER=0, PLAYER=1, TIE=2;

// Function Prototypes
int playerInput();
int computerInput();
int chooseWinner(int, int);
void displayResults(int, int, int);

//FUNCTION main
int main(){
	int computer, player,winner;
	// INTRODUCTION
	cout<<"\nWelcome to the Rock, Paper, Scissors Game\n"
		<<"-----------------------------------------\n";
	player = playerInput();
	computer = computerInput();
	winner = chooseWinner(player, computer);
	displayResults(player, computer, winner);
	return 0;
}

/******************
	FUNCTION playerInput
	
	The purpose of this function is to solicit
	user input in selecting Rock, Scissors or Paper
	
	No parameters are sent to the function.
	The function returns the user's input as an integer
	in the form of one of the pre-defined constants.
		
**********************/
int playerInput(){
    // FUNCTION SPECIFICATION
    // 1. LOOP USED TO VALIDATE USER INPUT
    // 2. PLAYER INPUTS ROCK, PAPER, SCISSORS VALUE
    // 3. DISPLAY PLAYER'S CHOICE CHOICE AS ROCK PAPER SCISSORS
    // 4. RETURNS INTEGER VALUE OF ROCK, PAPER, SCISSORS CHOSEN BY PLAYER
    return ROCK;// Possible Values: ROCK(0) or PAPER(1) or SCISSORS(2)
}

/******************
	FUNCTION computerInput
	
	The purpose of this function is to generate
	random input in the form of Rock, Scissors or Paper
	
	No parameters are sent to the function.
	The function returns the commputer's selection
	in the form of one of the pre-defined constants.
		
**********************/
int computerInput(){
	// CRITERIA
	// 1. COMPUTER RANDOMLY GENERATES ROCK, PAPER, SCISSORS VALUE
	// 2. DISPLAY COMPUTER'S CHOICE AS ROCK PAPER SCISSORS
	// 3. RETURNS INTEGER VALUE OF ROCK, PAPER, SCISSORS CHOSEN BY PLAYER
	return ROCK; // Possible Values: ROCK(0) or PAPER(1) or SCISSORS(2)
}

/******************
	FUNCTION chooseWinner
	
	The purpose of this function is to compare
	the values generated by User and Computer
	and return a constant indicating winner or tie.
		
	Parameters for user selection and random computer selection
	are sent to the function.
	The function returns the winner in the form 
	of one of the pre-defined constants.
		
**********************/
int chooseWinner(int, int){
	// CRITERIA
	// 1. COMPARE PLAYER AND COMPUTER SELECTIONS
	//    USING RULES FOR ROCK PAPER SCISSOR
	// 2. RETURNS Integer COMPUTER, PLAYER, OR TIE.
	return TIE; //COMPUTER=0, PLAYER=1, TIE=2;
}

/******************
	FUNCTION displayResults
	
	The purpose of this function is to display 
	the selections of the user, computer, and the winner

	Parameters for user selection, random computer selection,
	and winner are sent to the function in the form of integer 
	constants. The function does not return a value.
		
**********************/
void displayResults(int, int, int){
	// CRITERIA - Feel free to incorporate text-based graphics
	// 1. Display player's choice
	// 2. Display the computer's choice
	// 3. Display winner/tie
}

